services:
  - type: web
    name: pump-fun-streams
    env: python
    buildCommand: "pip install -r requirements.txt && npm install && npm run build:css"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7